name: Attach Artifact to Release

on:
  push:
    branches:
      - main

jobs:
  attach-artifact-to-release:
    uses: liquibase/build-logic/.github/workflows/extension-attach-artifact-release.yml@v0.5.7
    secrets: inherit
